# Generated by Django 5.0 on 2023-12-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_productcateogry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='day',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Price',
            field=models.CharField(default=-2011, max_length=10),
            preserve_default=False,
        ),
    ]
