# Generated by Django 5.0 on 2023-12-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_day_blogpost_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Product',
        ),
    ]
